[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_COLYSEUS_URL = "wss://vbnm1bbg-matheybackend.hf.space"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
